export const peru = [
    {name: 'Pedro Gallese', position: 'Goalkeeper', goals: 0},
    {name: 'Carlos Cáceda', position: 'Goalkeeper', goals: 0},
    {name: 'Patricio Álvarez', position: 'Goalkeeper', goals: 0},
    {name: 'Luis Advíncula', position: 'Defender', goals: 0},
    {name: 'Carlos Zambrano', position: 'Defender', goals: 0},
    {name: 'Miguel Trauco', position: 'Defender', goals: 0},
    {name: 'Aldo Corzo', position: 'Defender', goals: 0},
    {name: 'Luis Abram', position: 'Defender', goals: 0},
    {name: 'Anderson Santamaría ', position: 'Defender', goals: 0},
    {name: 'Marcos López', position: 'Defender', goals: 0},
    {name: 'Yoshimar Yotún', position: 'Defender', goals: 0},
    {name: 'Renato Tapia', position: 'Midfielder', goals: 0},
    {name: 'Pedro Aquino', position: 'Midfielder', goals: 0},
    {name: 'Carlos Ascues', position: 'Midfielder', goals: 0},
    {name: 'Cristian Benavente', position: 'Midfielder', goals: 0},
    {name: 'Sergio Peña', position: 'Midfielder', goals: 0},
    {name: 'Alexis Arias', position: 'Midfielder', goals: 0},
    {name: 'Paolo Guerrero', position: 'Forward', goals: 0},
    {name: 'Edison Flores', position: 'Forward', goals: 0},
    {name: 'Raúl Ruidíaz', position: 'Forward', goals: 0},
    {name: 'Andy Polo', position: 'Forward', goals: 0},
    {name: 'Gabriel Costa', position: 'Forward', goals: 0},
]